### ISSUE TITLE
My note doesn't display correctly - Iframes

### ISSUE THREAD

**Issue by afonsohocosta** [alangrainger/share-note#41]
I can't seem to get Iframes to work on shared notes. is this a known limitation of some sort? thanks!

In the below example, I used google.com as an example.

![image](https://github.com/alangrainger/share-note/assets/39400002/f4bb6529-2c9a-4f34-a522-e0556cf6b089)

This is a photo of the note in reading mode
![image](https://github.com/alangrainger/share-note/assets/39400002/a7298b84-29e2-4e20-a511-5b3f2cb63254)

And this is the shared link
https://share.note.sx/kxqdgz6l#X46+5qjxI2X9fzyQTQMQ32UyMMeORj6szIjx9PZRtts

wich displays like this:
![image](https://github.com/alangrainger/share-note/assets/39400002/1a8dd168-c162-403b-9a76-2fd56be435c2)

**Comment by alangrainger** [comment]
This is because Google (any most any other site) won't allow this, for security reasons.

If you look at the error in the console of your browser, you'll see something like:

```
The loading of “https://www.google.com/” in a frame is denied by “X-Frame-Options“ directive set to “sameorigin“.
```

This means that Google has a property called `X-Frame-Options` which only allows Google pages to be shown from Google domains, not from share.note.sx domain.

Desktop apps like Obsidian can do it, but not browsers.
