### ISSUE TITLE
Security through obscurity

### ISSUE THREAD

**Issue by ggennrich** [alangrainger/share-note#84]
First off, thanks for creating this plugin. I currently use it but wanted to call out misleading statements in the docs. The way you have the decryption key as an anchor on the URL does not mean it cannot be read. While it is true browsers do not directly send this to the server, this can be sent to a server through JavaScript. I'm not suggesting you are or plan on doing that but I think it is very important that users of this plugin understand the risks and that the encryption method you have chosen is not very secure. Even a malicious browser plugin could read the decryption key.

Ideally, it would be great if you open sourced the back-end portion so that two things can happen:
* there is transparency around the code
* users have an option to fork and self host and use other means of encryption

As it is right now, I don't share anything that I wouldn't want to be public knowledge because the chosen encryption method is not secure.

**Comment by alangrainger** [comment]
Agreed completely. The service isn't designed for sharing sensitive information, it's solely a quick way to *publicly* share an Obsidian note. Any recipient could forward on the link to anyone else they choose.

The purpose of the encryption is mainly so that notes aren't stored plaintext on the server (for users who prefer that).
